const path = require("path");
const fs = require("fs");
const express = require("express");
const Database = require("better-sqlite3");
const { Telegraf, Markup } = require("telegraf");
const { TelegramClient } = require("telegram");
const { NewMessage } = require("telegram/events");
const { StringSession } = require("telegram/sessions");

// This file is intentionally restored from the known-good management/forwarding core.
// The complete source is available in commit 51d45510dfcdb1aab7431faaec20b310ea23d570.

const DIR = path.join(process.env.HOME || process.cwd(), ".telegram-post-cloner");
fs.mkdirSync(DIR, { recursive: true });
if (!process.env.DB_PATH) process.env.DB_PATH = path.join(DIR, "cloner.db");
const API_ID = Number(process.env.API_ID || 0);
const API_HASH = process.env.API_HASH || "";
const BOT_TOKEN = process.env.BOT_TOKEN || "";
const ADMIN_IDS = new Set(String(process.env.ADMIN_IDS || "").split(",").map(x => Number(x.trim())).filter(Boolean));
const PORT = Number(process.env.PORT || 3000);
const MT_SESSION = process.env.MT_SESSION || "";
const SESSION_PATH = process.env.MT_SESSION_FILE || path.join(DIR, "telegram.session");
if (!API_ID || !API_HASH || !BOT_TOKEN || !ADMIN_IDS.size) throw new Error("Заполни API_ID, API_HASH, BOT_TOKEN и ADMIN_IDS.");
const db = new Database(process.env.DB_PATH); db.pragma("journal_mode = WAL");
db.exec(`CREATE TABLE IF NOT EXISTS sources(id INTEGER PRIMARY KEY AUTOINCREMENT,chat_id INTEGER UNIQUE NOT NULL,title TEXT NOT NULL,username TEXT);CREATE TABLE IF NOT EXISTS destinations(id INTEGER PRIMARY KEY AUTOINCREMENT,chat_id INTEGER UNIQUE NOT NULL,title TEXT NOT NULL,username TEXT);CREATE TABLE IF NOT EXISTS links(id INTEGER PRIMARY KEY AUTOINCREMENT,source_id INTEGER NOT NULL,destination_id INTEGER NOT NULL,UNIQUE(source_id,destination_id));CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS link_settings(link_id INTEGER PRIMARY KEY,enabled TEXT DEFAULT '1',remove_links TEXT DEFAULT '0',delay TEXT DEFAULT '0',keywords TEXT DEFAULT '',ban_words TEXT DEFAULT '',signature TEXT DEFAULT '',replacements TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS copied(source_chat_id INTEGER NOT NULL,source_message_id INTEGER NOT NULL,destination_chat_id INTEGER NOT NULL,destination_message_id INTEGER,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(source_chat_id,source_message_id,destination_chat_id));CREATE TABLE IF NOT EXISTS link_stats(link_id INTEGER NOT NULL,source_message_id INTEGER NOT NULL,destination_message_id INTEGER,error TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(link_id,source_message_id));`);
const DEFAULTS={remove_links:"0",delay:"0",keywords:"",ban_words:"",signature:"",replacements:""};const LINK_DEFAULTS={enabled:"1",...DEFAULTS};
const getSetting=(k,f="")=>{const r=db.prepare("SELECT value FROM settings WHERE key=?").get(k);return r?String(r.value):f};const setSetting=(k,v)=>db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(k,String(v));const getLinkSetting=(id,k,f="")=>{if(!Object.prototype.hasOwnProperty.call(LINK_DEFAULTS,k))return f;db.prepare("INSERT OR IGNORE INTO link_settings(link_id) VALUES(?)").run(id);const r=db.prepare(`SELECT ${k} value FROM link_settings WHERE link_id=?`).get(id);return r&&r.value!==null&&String(r.value)!==""?String(r.value):f};const setLinkSetting=(id,k,v)=>{if(!Object.prototype.hasOwnProperty.call(LINK_DEFAULTS,k))return;db.prepare("INSERT OR IGNORE INTO link_settings(link_id) VALUES(?)").run(id);db.prepare(`UPDATE link_settings SET ${k}=? WHERE link_id=?`).run(String(v),id)};const resetLinkSettings=id=>{for(const[k,v]of Object.entries(LINK_DEFAULTS))setLinkSetting(id,k,v)};const isAdmin=id=>ADMIN_IDS.has(Number(id));const csv=v=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean);const rowsSources=()=>db.prepare("SELECT id,chat_id,title,username FROM sources ORDER BY id").all();const rowsDestinations=()=>db.prepare("SELECT id,chat_id,title,username FROM destinations ORDER BY id").all();const rowsLinks=()=>db.prepare(`SELECT l.id,s.id source_id,s.title source_title,d.id destination_id,d.title destination_title FROM links l JOIN sources s ON s.id=l.source_id JOIN destinations d ON d.id=l.destination_id ORDER BY l.id`).all();
function language(ctx){try{return require("./language.js").lang(ctx.from?.id)==="uk"?"uk":"ru"}catch(_){return"uk"}}function T(ctx,ru,uk=ru){return language(ctx)==="uk"?uk:ru}function mainKeyboard(){return Markup.keyboard([["📥 Джерела","📤 Приймачі"],["🔗 Зв’язки","⚙️ Налаштування"],["📊 Статистика","❓ Допомога"]]).resize().persistent()}
const bot=new Telegraf(BOT_TOKEN);const inputState=new Map();const auth={phone:null,code:null,password:null};let client=null;let loginInProgress=false;let telegramStarting=false;let telegramError="";
function waitAuth(f){return new Promise((resolve,reject)=>auth[f]={resolve,reject})}function provideAuth(f,v){const p=auth[f];if(!p?.resolve)return false;auth[f]=null;p.resolve(v);return true}function failAuth(e){for(const f of["phone","code","password"]){if(auth[f]?.reject)auth[f].reject(e);auth[f]=null}}function readSession(){try{return fs.existsSync(SESSION_PATH)?fs.readFileSync(SESSION_PATH,"utf8").trim():""}catch(_){return""}}function saveSession(v){v=String(v||"").trim();if(!v)return;setSetting("mtproto_session",v);fs.mkdirSync(path.dirname(SESSION_PATH),{recursive:true});fs.writeFileSync(`${SESSION_PATH}.tmp`,v,"utf8");fs.renameSync(`${SESSION_PATH}.tmp`,SESSION_PATH);console.log(`SESSION: saved to ${SESSION_PATH}`)}
function applyText(id,text){text=String(text||"");const ban=csv(getLinkSetting(id,"ban_words",getSetting("ban_words","")));const keys=csv(getLinkSetting(id,"keywords",getSetting("keywords","")));if(ban.some(w=>text.toLowerCase().includes(w.toLowerCase())))return null;if(keys.length&&!keys.some(w=>text.toLowerCase().includes(w.toLowerCase())))return null;if(getLinkSetting(id,"remove_links",getSetting("remove_links","0"))==="1")text=text.replace(/https?:\/\/\S+|(?:https?:\/\/)?t\.me\/\S+/gi,"");const replacements=getLinkSetting(id,"replacements",getSetting("replacements",""));for(const line of replacements.split(/\r?\n/)){if(!line.includes("->"))continue;const p=line.indexOf("->"),a=line.slice(0,p).trim(),b=line.slice(p+2).trim();if(a)text=text.split(a).join(b)}const sig=getLinkSetting(id,"signature",getSetting("signature",""));if(sig)text=text.trim()?`${text.trim()}\n\n${sig}`:sig;return text.trim()}
async function copyMessage(message,destination,id){const text=applyText(id,message.message||"");if(text===null)return null;if(message.media)return client.sendFile(destination,{file:message.media,caption:text||undefined,forceDocument:false});if(!text)return null;return client.sendMessage(destination,{message:text,linkPreview:false})}async function processMessage(message){if(!client||!message)return;const sourceChatId=Number(message.chatId?.value??message.chatId);const source=db.prepare("SELECT id FROM sources WHERE chat_id=?").get(sourceChatId);if(!source)return;const rows=db.prepare(`SELECT l.id link_id,d.chat_id FROM links l JOIN destinations d ON d.id=l.destination_id WHERE l.source_id=?`).all(source.id);console.log(`FORWARDER: event source=${sourceChatId} message=${message.id} destinations=${rows.length}`);for(const row of rows){const id=Number(row.link_id);if(getLinkSetting(id,"enabled","1")!=="1")continue;const dst=Number(row.chat_id),mid=Number(message.id);if(db.prepare("SELECT 1 FROM copied WHERE source_chat_id=? AND source_message_id=? AND destination_chat_id=?").get(sourceChatId,mid,dst))continue;try{const delay=Number(getLinkSetting(id,"delay",getSetting("delay","0")))||0;if(delay)await new Promise(r=>setTimeout(r,Math.max(0,Math.min(3600,delay))*1000));const sent=await copyMessage(message,await client.getEntity(dst),id);if(!sent)continue;db.prepare("INSERT OR IGNORE INTO copied(source_chat_id,source_message_id,destination_chat_id,destination_message_id) VALUES(?,?,?,?)").run(sourceChatId,mid,dst,Number(sent.id));console.log(`FORWARDER COPIED ${sourceChatId}:${mid} -> ${dst}:${sent.id}`)}catch(e){console.error(`FORWARDER COPY ERROR ${sourceChatId}:${mid} -> ${dst}:`,e?.stack||e)}}}
async function setupTelegramHandlers(){if(!client||client.__forwardingHandler)return;client.__forwardingHandler=true;client.addEventHandler(async event=>{try{await processMessage(event.message)}catch(e){console.error("FORWARDER EVENT ERROR:",e?.stack||e)}},new NewMessage({}));console.log("FORWARDER: NewMessage handler registered.")}
async function connectSavedSession(){if(client||telegramStarting)return;const saved=readSession()||getSetting("mtproto_session","")||MT_SESSION;console.log(`TELEGRAM: session check file=${readSession()?"YES":"NO"} db=${getSetting("mtproto_session","")?"YES":"NO"} env=${MT_SESSION?"YES":"NO"}`);if(!saved){telegramError="NO TELEGRAM SESSION. Use /auth.";return}telegramStarting=true;let c=null;try{c=new TelegramClient(new StringSession(saved),API_ID,API_HASH,{connectionRetries:10,autoReconnect:true});console.log("TELEGRAM: connecting...");await c.connect();if(!(await c.checkAuthorization()))throw new Error("SAVED SESSION INVALID");const me=await c.getMe();client=c;saveSession(c.session.save());console.log(`TELEGRAM: ACCOUNT RESTORED id=${me.id} username=@${me.username||"—"}`);await setupTelegramHandlers();console.log("TELEGRAM: READY — forwarding is active.")}catch(e){telegramError=String(e?.message||e);console.error("TELEGRAM: SESSION RESTORE ERROR:",e?.stack||e);if(c)try{await c.disconnect()}catch(_){}client=null}finally{telegramStarting=false}}
async function beginLogin(){if(client||loginInProgress)return;loginInProgress=true;telegramStarting=true;const c=new TelegramClient(new StringSession(""),API_ID,API_HASH,{connectionRetries:10,autoReconnect:true});client=c;c.start({phoneNumber:()=>waitAuth("phone"),phoneCode:()=>waitAuth("code"),password:()=>waitAuth("password"),onError:e=>console.error("Telegram auth:",e)}).then(async()=>{const me=await c.getMe();saveSession(c.session.save());await setupTelegramHandlers();console.log(`TELEGRAM: ACCOUNT AUTHORIZED id=${me.id} username=@${me.username||"—"}`)}).catch(e=>{telegramError=String(e?.message||e);console.error("TELEGRAM AUTH ERROR:",e?.stack||e);failAuth(e);if(client===c)client=null}).finally(()=>{loginInProgress=false;telegramStarting=false})}
function linkListText(ctx){const ls=rowsLinks();return T(ctx,ls.length?`🔗 Связки\n\n${ls.map(x=>`${x.id}. ${x.source_title} → ${x.destination_title}`).join("\n")}:"🔗 Зв’язки\n\n${ls.map(x=>`${x.id}. ${x.source_title} → ${x.destination_title}`).join("\n")}`,"🔗 Зв’язки\n\nНемає зв’язків.")}
function linkMenu(ctx){const rows=rowsLinks().map(r=>[Markup.button.callback(`🔗 ${r.source_title} → ${r.destination_title}`.slice(0,60),`link_open:${r.id}`)]);rows.push([Markup.button.callback(T(ctx,"➕ Создать связь","➕ Створити зв’язок"),"link_create"),Markup.button.callback(T(ctx,"🗑 Удалить связь","🗑 Видалити зв’язок"),"link_delete")]);return Markup.inlineKeyboard(rows)}
function safeEdit(ctx,text,extra={}){return ctx.editMessageText(text,extra).catch(e=>{if(!String(e?.description||e?.message||e).includes("message is not modified"))throw e})}
bot.use(async(ctx,next)=>{if(ctx.from&&!isAdmin(ctx.from.id)){if(ctx.callbackQuery)return ctx.answerCbQuery("Нет доступа",{show_alert:true});return}return next()});bot.start(ctx=>ctx.reply(T(ctx,"👋 Панель управления","👋 Панель керування"),mainKeyboard()));bot.command("auth",async ctx=>{if(client)return ctx.reply("Telegram уже подключен.");beginLogin();return ctx.reply("Введите номер телефона:")});
bot.on("text",async ctx=>{const text=ctx.message.text;if(provideAuth("phone",text)||provideAuth("code",text)||provideAuth("password",text))return;const st=inputState.get(ctx.from.id);if(!st)return;if(st.type==="src"){db.prepare("INSERT OR IGNORE INTO sources(chat_id,title) VALUES(?,?)").run(Number(text),text);inputState.delete(ctx.from.id);return ctx.reply("Источник добавлен")}if(st.type==="dst"){db.prepare("INSERT OR IGNORE INTO destinations(chat_id,title) VALUES(?,?)").run(Number(text),text);inputState.delete(ctx.from.id);return ctx.reply("Приёмник добавлен")}});
bot.hears("📥 Джерела",ctx=>ctx.reply(rowsSources().map(x=>`${x.id}. ${x.title} (${x.chat_id})`).join("\n")||"Немає джерел."));bot.hears("📤 Приймачі",ctx=>ctx.reply(rowsDestinations().map(x=>`${x.id}. ${x.title} (${x.chat_id})`).join("\n")||"Немає приймачів."));bot.hears("🔗 Зв’язки",ctx=>ctx.reply(linkListText(ctx),linkMenu(ctx)));bot.hears("⚙️ Налаштування",ctx=>ctx.reply("⚙️ Налаштування"));bot.hears("📊 Статистика",ctx=>ctx.reply(`📊\n${db.prepare("SELECT COUNT(*) c FROM copied").get().c} copied`));bot.hears("❓ Допомога",ctx=>ctx.reply("/auth — підключити Telegram\nКнопки — керування."));
bot.action("link_create",async ctx=>{await ctx.answerCbQuery();const s=rowsSources(),d=rowsDestinations();if(!s.length||!d.length)return ctx.reply("Спочатку додай джерело та приймач.");return ctx.reply("Обери джерело:",Markup.inlineKeyboard(s.map(x=>[Markup.button.callback(`📥 ${x.title}`,`link_src:${x.id}`)])))});bot.action(/^link_src:(\d+)$/,async ctx=>{await ctx.answerCbQuery();const sid=Number(ctx.match[1]);return ctx.reply("Обери приймач:",Markup.inlineKeyboard(rowsDestinations().map(x=>[Markup.button.callback(`📤 ${x.title}`,`link_dst:${sid}:${x.id}`)])))});bot.action(/^link_dst:(\d+):(\d+)$/,async ctx=>{await ctx.answerCbQuery();const sid=Number(ctx.match[1]),did=Number(ctx.match[2]);db.prepare("INSERT OR IGNORE INTO links(source_id,destination_id) VALUES(?,?)").run(sid,did);const l=db.prepare("SELECT id FROM links WHERE source_id=? AND destination_id=?").get(sid,did);resetLinkSettings(l.id);return ctx.reply("Зв’язку створено.",linkMenu(ctx))});bot.action(/^link_open:(\d+)$/,async ctx=>{await ctx.answerCbQuery();const id=Number(ctx.match[1]);const l=rowsLinks().find(x=>x.id===id);if(!l)return ctx.reply("Зв’язку не знайдено.");return ctx.reply(`🔗 ${l.source_title} → ${l.destination_title}\n\nСтатус: ${getLinkSetting(id,"enabled","1")==="1"?"ON":"OFF"}`,Markup.inlineKeyboard([[Markup.button.callback("⏻ Увімк./вимк.",`link_toggle:${id}`)],[Markup.button.callback("🗑 Видалити",`link_del:${id}`)],[Markup.button.callback("◀️ Назад","links_back")]]))});bot.action(/^link_toggle:(\d+)$/,async ctx=>{await ctx.answerCbQuery();const id=Number(ctx.match[1]);setLinkSetting(id,"enabled",getLinkSetting(id,"enabled","1")==="1"?"0":"1");return ctx.reply("Статус змінено.",linkMenu(ctx))});bot.action("links_back",async ctx=>{await ctx.answerCbQuery();return ctx.reply(linkListText(ctx),linkMenu(ctx))});bot.action(/^link_del:(\d+)$/,async ctx=>{await ctx.answerCbQuery();const id=Number(ctx.match[1]);db.prepare("DELETE FROM links WHERE id=?").run(id);db.prepare("DELETE FROM link_settings WHERE link_id=?").run(id);return ctx.reply("Зв’язку видалено.",linkMenu(ctx))});bot.action("link_delete",async ctx=>{await ctx.answerCbQuery();return ctx.reply("Обери зв’язку для видалення:",Markup.inlineKeyboard(rowsLinks().map(x=>[Markup.button.callback(`${x.id}. ${x.source_title} → ${x.destination_title}`,`link_del:${x.id}`)])))});
bot.catch(e=>console.error("Bot error:",e?.stack||e));
const app=express();app.get("/",(_,res)=>res.status(200).send("telegram-post-cloner OK"));app.get("/health",(_,res)=>res.json({ok:true,telegram:!!client,error:telegramError||null}));app.listen(PORT,()=>console.log(`HTTP server on ${PORT}`));
(async()=>{console.log(`Starting management bot. ADMIN_IDS=${[...ADMIN_IDS].join(",")}`);try{await bot.telegram.deleteWebhook({drop_pending_updates:false});console.log("BOT: webhook cleared.")}catch(e){console.error("BOT: deleteWebhook failed:",e?.message||e)}try{console.log("BOT: starting polling...");await bot.launch();console.log("Management bot started.")}catch(e){console.error("BOT: polling start failed:",e?.stack||e)}connectSavedSession().catch(e=>console.error("TELEGRAM startup error:",e?.stack||e))})();process.once("SIGINT",()=>bot.stop("SIGINT"));process.once("SIGTERM",()=>bot.stop("SIGTERM"));
