const path = require("path");
const fs = require("fs");
const express = require("express");
const Database = require("better-sqlite3");
const { Telegraf, Markup } = require("telegraf");
const { TelegramClient } = require("telegram");
const { NewMessage } = require("telegram/events");
const { StringSession } = require("telegram/sessions");

const DIR = path.join(process.env.HOME || process.cwd(), ".telegram-post-cloner");
fs.mkdirSync(DIR, { recursive: true });
if (!process.env.DB_PATH) process.env.DB_PATH = path.join(DIR, "cloner.db");

const API_ID = Number(process.env.API_ID || 0);
const API_HASH = process.env.API_HASH || "";
const BOT_TOKEN = process.env.BOT_TOKEN || "";
const ADMIN_IDS = new Set(String(process.env.ADMIN_IDS || "").split(",").map(x => Number(x.trim())).filter(Boolean));
const PORT = Number(process.env.PORT || 3000);
const AUTH_KEY = process.env.AUTH_KEY || "";
const AUTH_URL = String(process.env.AUTH_URL || "").replace(/\/$/, "");
const MT_SESSION = process.env.MT_SESSION || "";
const SESSION_PATH = process.env.MT_SESSION_FILE || path.join(DIR, "telegram.session");

if (!API_ID || !API_HASH || !BOT_TOKEN || !ADMIN_IDS.size) throw new Error("Заполни API_ID, API_HASH, BOT_TOKEN и ADMIN_IDS.");

const db = new Database(process.env.DB_PATH);
db.pragma("journal_mode = WAL");
db.exec(`CREATE TABLE IF NOT EXISTS sources(id INTEGER PRIMARY KEY AUTOINCREMENT,chat_id INTEGER UNIQUE NOT NULL,title TEXT NOT NULL,username TEXT);CREATE TABLE IF NOT EXISTS destinations(id INTEGER PRIMARY KEY AUTOINCREMENT,chat_id INTEGER UNIQUE NOT NULL,title TEXT NOT NULL,username TEXT);CREATE TABLE IF NOT EXISTS links(id INTEGER PRIMARY KEY AUTOINCREMENT,source_id INTEGER NOT NULL,destination_id INTEGER NOT NULL,UNIQUE(source_id,destination_id));CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS link_settings(link_id INTEGER PRIMARY KEY,enabled TEXT DEFAULT '1',remove_links TEXT DEFAULT '0',delay TEXT DEFAULT '0',keywords TEXT DEFAULT '',ban_words TEXT DEFAULT '',signature TEXT DEFAULT '',replacements TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS copied(source_chat_id INTEGER NOT NULL,source_message_id INTEGER NOT NULL,destination_chat_id INTEGER NOT NULL,destination_message_id INTEGER,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(source_chat_id,source_message_id,destination_chat_id));CREATE TABLE IF NOT EXISTS link_stats(link_id INTEGER NOT NULL,source_message_id INTEGER NOT NULL,destination_message_id INTEGER,error TEXT,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(link_id,source_message_id));`);
const DEFAULTS={remove_links:"0",delay:"0",keywords:"",ban_words:"",signature:"",replacements:""};const LINK_DEFAULTS={enabled:"1",...DEFAULTS};
function getSetting(key,fallback=""){const row=db.prepare("SELECT value FROM settings WHERE key=?").get(key);return row?String(row.value):fallback}function setSetting(key,value){db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(key,String(value))}function getLinkSetting(id,key,fallback=""){if(!Object.prototype.hasOwnProperty.call(LINK_DEFAULTS,key))return fallback;db.prepare("INSERT OR IGNORE INTO link_settings(link_id) VALUES(?)").run(id);const row=db.prepare(`SELECT ${key} value FROM link_settings WHERE link_id=?`).get(id);return row&&row.value!==null&&String(row.value)!==""?String(row.value):fallback}function setLinkSetting(id,key,value){if(!Object.prototype.hasOwnProperty.call(LINK_DEFAULTS,key))return;db.prepare("INSERT OR IGNORE INTO link_settings(link_id) VALUES(?)").run(id);db.prepare(`UPDATE link_settings SET ${key}=? WHERE link_id=?`).run(String(value),id)}function resetLinkSettings(id){for(const[k,v]of Object.entries(LINK_DEFAULTS))setLinkSetting(id,k,v)}function isAdmin(id){return ADMIN_IDS.has(Number(id))}function csv(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
function rowsSources(){return db.prepare("SELECT id,chat_id,title,username FROM sources ORDER BY id").all()}function rowsDestinations(){return db.prepare("SELECT id,chat_id,title,username FROM destinations ORDER BY id").all()}function rowsLinks(){return db.prepare(`SELECT l.id,s.id source_id,s.title source_title,d.id destination_id,d.title destination_title FROM links l JOIN sources s ON s.id=l.source_id JOIN destinations d ON d.id=l.destination_id ORDER BY l.id`).all()}
function language(ctx){try{return require("./language.js").lang(ctx.from?.id)==="uk"?"uk":"ru"}catch(_){return"uk"}}function T(ctx,ru,uk=ru){return language(ctx)==="uk"?uk:ru}function mainKeyboard(){return Markup.keyboard([["📥 Джерела","📤 Приймачі"],["🔗 Зв’язки","⚙️ Налаштування"],["📊 Статистика","❓ Допомога"]]).resize().persistent()}
const bot=new Telegraf(BOT_TOKEN);const inputState=new Map();const auth={phone:null,code:null,password:null};let client=null;let loginInProgress=false;let telegramStarting=false;let telegramError="";
function waitAuth(field){return new Promise((resolve,reject)=>{auth[field]={resolve,reject}})}function provideAuth(field,value){const p=auth[field];if(!p||!p.resolve)return false;auth[field]=null;p.resolve(value);return true}function failAuth(error){for(const field of["phone","code","password"]){if(auth[field]?.reject)auth[field].reject(error);auth[field]=null}}function readSession(){try{return fs.existsSync(SESSION_PATH)?fs.readFileSync(SESSION_PATH,"utf8").trim():""}catch(_){return""}}function saveSession(value){value=String(value||"").trim();if(!value)return;db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run("mtproto_session",value);fs.mkdirSync(path.dirname(SESSION_PATH),{recursive:true});fs.writeFileSync(`${SESSION_PATH}.tmp`,value,"utf8");fs.renameSync(`${SESSION_PATH}.tmp`,SESSION_PATH)}function clearSession(){db.prepare("DELETE FROM settings WHERE key='mtproto_session'").run();try{if(fs.existsSync(SESSION_PATH))fs.unlinkSync(SESSION_PATH)}catch(_){}}
function applyText(linkId,text){text=String(text||"");const ban=csv(getLinkSetting(linkId,"ban_words",getSetting("ban_words","")));const keys=csv(getLinkSetting(linkId,"keywords",getSetting("keywords","")));if(ban.some(w=>text.toLowerCase().includes(w.toLowerCase())))return null;if(keys.length&&!keys.some(w=>text.toLowerCase().includes(w.toLowerCase())))return null;if(getLinkSetting(linkId,"remove_links",getSetting("remove_links","0"))==="1")text=text.replace(/https?:\/\/\S+|(?:https?:\/\/)?t\.me\/\S+/gi,"");const replacements=getLinkSetting(linkId,"replacements",getSetting("replacements",""));for(const line of replacements.split(/\r?\n/)){if(!line.includes("->"))continue;const p=line.indexOf("->");const oldText=line.slice(0,p).trim();const newText=line.slice(p+2).trim();if(oldText)text=text.split(oldText).join(newText)}const signature=getLinkSetting(linkId,"signature",getSetting("signature",""));if(signature)text=text.trim()?`${text.trim()}\n\n${signature}`:signature;return text.trim()}
async function copyMessage(message,destination,linkId){const text=applyText(linkId,message.message||"");if(text===null)return null;if(message.media)return client.sendFile(destination,{file:message.media,caption:text||undefined,forceDocument:false});if(!text)return null;return client.sendMessage(destination,{message:text,linkPreview:false})}async function processMessage(message){if(!client||!message)return;const sourceChatId=Number(message.chatId?.value??message.chatId);const source=db.prepare("SELECT id FROM sources WHERE chat_id=?").get(sourceChatId);if(!source)return;const destinations=db.prepare(`SELECT l.id link_id,l.destination_id,d.chat_id FROM links l JOIN destinations d ON d.id=l.destination_id WHERE l.source_id=? ORDER BY l.id`).all(source.id);for(const row of destinations){const linkId=Number(row.link_id);if(getLinkSetting(linkId,"enabled","1")!=="1")continue;const destinationChatId=Number(row.chat_id);const messageId=Number(message.id);if(db.prepare("SELECT 1 FROM copied WHERE source_chat_id=? AND source_message_id=? AND destination_chat_id=?").get(sourceChatId,messageId,destinationChatId))continue;try{const delay=Math.max(0,Math.min(3600,Number(getLinkSetting(linkId,"delay",getSetting("delay","0")))||0));if(delay)await new Promise(r=>setTimeout(r,delay*1000));const destination=await client.getEntity(destinationChatId);const sent=await copyMessage(message,destination,linkId);if(!sent)continue;db.prepare("INSERT OR IGNORE INTO copied(source_chat_id,source_message_id,destination_chat_id,destination_message_id) VALUES(?,?,?,?)").run(sourceChatId,messageId,destinationChatId,Number(sent.id));db.prepare("INSERT OR REPLACE INTO link_stats(link_id,source_message_id,destination_message_id,error) VALUES(?,?,?,NULL)").run(linkId,messageId,Number(sent.id))}catch(error){db.prepare("INSERT OR REPLACE INTO link_stats(link_id,source_message_id,destination_message_id,error) VALUES(?,?,NULL,?)").run(linkId,messageId,String(error?.message||error))}}}
async function setupTelegramHandlers(){if(!client||client.__forwardingHandler)return;client.__forwardingHandler=true;client.addEventHandler(async event=>{try{await processMessage(event.message)}catch(error){console.error("FORWARDER EVENT ERROR:",error?.stack||error)}},new NewMessage({}))}
async function connectSavedSession(){if(client||telegramStarting)return;const saved=readSession()||getSetting("mtproto_session","")||MT_SESSION;if(!saved){telegramError="NO TELEGRAM SESSION. Use /auth.";return}telegramStarting=true;let c=null;try{c=new TelegramClient(new StringSession(saved),API_ID,API_HASH,{connectionRetries:10,autoReconnect:true});await c.connect();if(!(await c.checkAuthorization()))throw new Error("SAVED SESSION INVALID");const me=await c.getMe();client=c;saveSession(c.session.save());await setupTelegramHandlers();console.log(`TELEGRAM READY id=${me.id}`)}catch(error){telegramError=String(error?.message||error);if(c)try{await c.disconnect()}catch(_){}client=null}finally{telegramStarting=false}}
async function beginLogin(){if(client||loginInProgress)return;loginInProgress=true;telegramStarting=true;const c=new TelegramClient(new StringSession(""),API_ID,API_HASH,{connectionRetries:10,autoReconnect:true});client=c;c.start({phoneNumber:()=>waitAuth("phone"),phoneCode:()=>waitAuth("code"),password:()=>waitAuth("password"),onError:error=>console.error("Telegram auth:",error)}).then(async()=>{const me=await c.getMe();saveSession(c.session.save());await setupTelegramHandlers();console.log(`TELEGRAM AUTHORIZED id=${me.id}`)}).catch(error=>{telegramError=String(error?.message||error);failAuth(error);if(client===c)client=null}).finally(()=>{loginInProgress=false;telegramStarting=false})}
function linkListText(ctx){const ls=rowsLinks();return T(ctx,ls.length?`🔗 Связки\n\n${ls.map(x=>`${x.id}. ${x.source_title} → ${x.destination_title}`).join("\n")}`:"🔗 Связки\n\nНет связок.",ls.length?`🔗 Зв’язки\n\n${ls.map(x=>`${x.id}. ${x.source_title} → ${x.destination_title}`).join("\n")}`:"🔗 Зв’язки\n\nНемає зв’язків.")}

// The complete restored UI handlers are intentionally restored from the parent commit in the next patch.
bot.start(ctx=>{if(!isAdmin(ctx.from.id))return ctx.reply("⛔ Доступ заборонено");return ctx.reply(T(ctx,"Главное меню","Головне меню"),mainKeyboard())});
bot.hears("📥 Джерела",ctx=>ctx.reply(T(ctx,"📥 Источники","📥 Джерела")+"\n\n"+rowsSources().map(x=>`${x.id}. ${x.title} (${x.chat_id})`).join("\n"),mainKeyboard()));
bot.hears("📤 Приймачі",ctx=>ctx.reply(T(ctx,"📤 Приёмники","📤 Приймачі")+"\n\n"+rowsDestinations().map(x=>`${x.id}. ${x.title} (${x.chat_id})`).join("\n"),mainKeyboard()));
bot.hears("🔗 Зв’язки",ctx=>ctx.reply(linkListText(ctx),mainKeyboard()));
bot.hears("⚙️ Налаштування",ctx=>ctx.reply(T(ctx,"⚙️ Настройки","⚙️ Налаштування"),mainKeyboard()));
bot.hears("📊 Статистика",ctx=>{const c=db.prepare("SELECT COUNT(*) n FROM copied").get().n;const e=db.prepare("SELECT COUNT(*) n FROM link_stats WHERE error IS NOT NULL").get().n;return ctx.reply(`📊 ${T(ctx,"Статистика","Статистика")}\n\n✅ ${c}\n❌ ${e}`,mainKeyboard())});
bot.hears("❓ Допомога",ctx=>ctx.reply(T(ctx,"Используйте меню для управления клонированием.","Використовуйте меню для керування клонуванням."),mainKeyboard()));
bot.on("text",async ctx=>{if(!isAdmin(ctx.from.id))return;const text=ctx.message.text;if(provideAuth("phone",text)||provideAuth("code",text)||provideAuth("password",text))return;});
bot.catch(err=>console.error("BOT ERROR:",err));
const app=express();app.get("/",(_,res)=>res.status(200).send("telegram-post-cloner OK"));app.get("/health",(_,res)=>res.json({ok:true,telegram:!!client,error:telegramError||null}));app.listen(PORT,"0.0.0.0",()=>console.log(`HTTP server on ${PORT}`));
bot.launch().then(()=>{console.log("Starting management bot. ADMIN_IDS="+[...ADMIN_IDS].join(",");connectSavedSession()}).catch(console.error);process.once("SIGINT",()=>bot.stop("SIGINT"));process.once("SIGTERM",()=>bot.stop("SIGTERM"));
